version: '3'

services:
  app1:
    build: .
    container_name: app1
    ports:
      - "8001:8000"  # Maps the internal FastAPI port 8000 to 8001 on the host
    environment:
      - UVICORN_WORKERS=2

  app2:
    build: .
    container_name: app2
    ports:
      - "8002:8000"  # Maps the internal FastAPI port 8000 to 8002 on the host
    environment:
      - UVICORN_WORKERS=2

  app3:
    build: .
    container_name: app3
    ports:
      - "8003:8000"  # Maps the internal FastAPI port 8000 to 8003 on the host
    environment:
      - UVICORN_WORKERS=2

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"  # Expose port 80 of NGINX as 8080 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Bind the NGINX configuration file
    depends_on:
      - app1
      - app2
      - app3

